[package]
name = "main_crate"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.0" }
macros = { path = "../macros" }
bevy_utils = { path = "../bevy_utils" }
models_3d = { path = "../models_3d" }
